#ifndef CLAW_H
#define CLAW_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

class Claw: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* motor;
	DigitalInput* leftClawLimit;
	DigitalInput* rightClawLimit;
	Encoder* encoder;
	static double PICKUP_DIST;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Claw();
	void InitDefaultCommand();
	void Open();
	void Close();
	void Stop();
	bool IsOpen();
	bool HitObject();
};

#endif
