// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OpenClaw.h"

OpenClaw::OpenClaw() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::claw);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void OpenClaw::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void OpenClaw::Execute() {
	Robot::claw->Open();
}

/** see if you can make this better by using the encoder position rather than time
 * on a real robot, this would be a very bad way to do things!
 */
bool OpenClaw::IsFinished() {
	return Robot::claw->IsOpen();
}

// Called once after isFinished returns true
void OpenClaw::End() {
	//don't stop in simulation, because they won't hold their position
#ifdef REAL
	Robot::claw->Stop();
#endif
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void OpenClaw::Interrupted() {
	End();

}
