// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "TurnThroughAngle.h"

TurnThroughAngle::TurnThroughAngle(double angle) {
	Requires(Robot::driveTrain);
	this->angle = angle;
}

// Called just before this Command runs the first time
void TurnThroughAngle::Initialize() {
	startingAngle = Robot::driveTrain->GetAngle();
	// getAngle goes from -180 to 180, we must compensate for this
	if (angle + startingAngle >= 180) {
		endAngle = (angle + startingAngle) % 180 - 180;
	} else {
		endAngle = angle + startingAngle;
	}
}

// Called repeatedly when this Command is scheduled to run
void TurnThroughAngle::Execute() {
	if (angle > 0) {
		Robot::driveTrain->Drive(-0.95, 0.95);
	} else {
		Robot::driveTrain->Drive(0.95, -0.95);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool TurnThroughAngle::IsFinished() {
	return abs(Robot::driveTrain->GetAngle() - endAngle) < 0.5;
}

// Called once after isFinished returns true
void TurnThroughAngle::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnThroughAngle::Interrupted() {

}
