// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

#include <Buttons/JoystickButton.h>
#include <Joystick.h>
#include <SmartDashboard/SmartDashboard.h>

#include "Commands/Auto.h"
#include "Commands/CloseClaw.h"
#include "Commands/DriveStraightDistance.h"
#include "Commands/DriveStraightTillTote.h"
#include "Commands/OpenClaw.h"
#include "Commands/SetElevatorSetpoint.h"
#include "Commands/TurnThroughAngle.h"


/**
 * This class contains all the objects for the joysticks and joystick buttons
 *
 *
                   ,-'.,'`.                         ,'`.,'-.
                 ,'    `.OPEN CLAW          CLOSE CLAW,'    `.
               ,'        `-._   `'-~.,___,.~-'`   _,-'__      `.       _
              /   _____      '-.,_   _____   _,.-'   /  `.      \       |
             /  ,' ___ `.       ,',-'     `-.'.      |HIGH  __   \      |
            /  / ,' ' `. \    ,','           `.`.    `.__/ /  `.  \     |
           /   | |LEFT | |   / /     _   _     \ \    __   |MED2   \    |
          /    \ `DRIVE' /   |!  \/ |_) / \ \/  |!   /  `. `.__/    \   |
         /      `._____,'    |!  /\ |_) \_/ /\  |!   |MED1  __       \  | Elevator Positions
         !            ___    \ \               / /   `.__/ /  `.     |  |
         !         ,-'___`-.  `.`.           ,','          |LOW|     |  |
         |        / ,'   `. \   `.`-._____,-','       ___  `.__/     | _|
         |       | / -' '- \ | ,`             `.    ,'___`.          |
         |       | \ -. .- / |'                 `. / RIGHT \         |
         |        \ `.___,' /     ___     ___     `\ DRIVE /         |
         |         `-.___,-'     (___)   (___)      `.___.'          |
         |             ,'`-._                     _,-'`.             |
          \          ,'      `'~-.,_________,.-~'`      `.          /
           `.      ,'                                     `.      ,'
             `-__,'                                         `.__.'


 *
 */
OI::OI() {

	// Process operator interface input here.
	gamepad = new Joystick(0);
	getToteButton = new JoystickButton(gamepad, 1);
	getBinButton = new JoystickButton(gamepad, 2);
	liftToteButton = new JoystickButton(gamepad, 3);
	liftBinButton = new JoystickButton(gamepad, 4);
	openClaw = new JoystickButton(gamepad, 5);
	closeClaw = new JoystickButton(gamepad, 6);

	openClaw->WhenPressed(new OpenClaw());
	closeClaw->WhenPressed(new CloseClaw());

	getToteButton->WhenPressed(new SetElevatorSetpoint(Elevator::getTote));
	liftToteButton->WhenPressed(new SetElevatorSetpoint(Elevator::liftTote));
	getBinButton->WhenPressed(new SetElevatorSetpoint(Elevator::getBin));
	liftBinButton->WhenPressed(new SetElevatorSetpoint(Elevator::liftBin));

}

Joystick* OI::GetGamepad() {
	return gamepad;
}
