#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* gamepad;
	JoystickButton* getBinButton;
	JoystickButton* liftBinButton;
	JoystickButton* getToteButton;
	JoystickButton* liftToteButton;
	JoystickButton* openClaw;
	JoystickButton* closeClaw;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* GetGamepad();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

};

#endif
